# Generated by Django 5.0.3 on 2024-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.treicamile.ro/wp-content/uploads/2021/11/food-placeholder.png', max_length=500),
        ),
    ]
